<?php
//
// File generated by Dolibarr installer 3.5.2 on Jan 22, 2015
//
// Take a look at conf.php.example file for an example of conf.php file
// and explanations for all possibles parameters.
//
$dolibarr_main_url_root='http://_ENGINES_$fqdn';
$dolibarr_main_document_root='/home/app';
//$dolibarr_main_url_root_alt='/custom';
//$dolibarr_main_document_root_alt='/home/app/custom';
$dolibarr_main_data_root='/home/app/documents';
$dolibarr_main_db_host='_ENGINES_dbhost';
$dolibarr_main_db_port='';
$dolibarr_main_db_name='_ENGINES_dbname';
$dolibarr_main_db_prefix='llx_';
$dolibarr_main_db_user='_ENGINES_dbuser';
$dolibarr_main_db_pass='_ENGINES_dbpasswd';
$dolibarr_main_db_type='mysqli';
$dolibarr_main_db_character_set='latin1';
$dolibarr_main_db_collation='latin1_swedish_ci';
$dolibarr_main_authentication='dolibarr';

// Specific settings
$dolibarr_main_prod='0';
$dolibarr_nocsrfcheck='0';
$dolibarr_main_force_https='0';
$dolibarr_main_cookie_cryptkey='a19a815aa35d0488093f566e4bb52eaf';
$dolibarr_mailing_limit_sendbyweb='0';

//$dolibarr_lib_TCPDF_PATH='';
//$dolibarr_lib_FPDF_PATH='';
//$dolibarr_lib_FPDI_PATH='';
//$dolibarr_lib_ADODB_PATH='';
//$dolibarr_lib_GEOIP_PATH='';
//$dolibarr_lib_NUSOAP_PATH='';
//$dolibarr_lib_PHPEXCEL_PATH='';
//$dolibarr_lib_ODTPHP_PATH='';
//$dolibarr_lib_ODTPHP_PATHTOPCLZIP='';
//$dolibarr_js_CKEDITOR='';
//$dolibarr_js_JQUERY='';
//$dolibarr_js_JQUERY_UI='';
//$dolibarr_js_JQUERY_FLOT='';

//$dolibarr_font_DOL_DEFAULT_TTF='';
//$dolibarr_font_DOL_DEFAULT_TTF_BOLD='';
?>
